name: BNK Bot
version: "1.0"
slug: bnk_bot
description: Telegram bot for production and waste tracking
arch:
  - armv7
  - aarch64
  - amd64
startup: services
boot: auto
options:
  TELEGRAM_TOKEN: "8199873882:AAE4x2ARLf7bR0fC9ykeOyHsrinT9JPIdRM"
schema:
  TELEGRAM_TOKEN: str